Feature: Merchant_Checkout

    Scenario: Assisted Checkout
        Given As a user with Role "<userRole>" for "<merchantName>" I can successfully login to the "<applicationName>" application
        When I can successfully create a plan in "<currencyCode>" currency having "<redemptionDate>" date and "<planTotal>" plan total and selected settings "<depositSetting>","<installmentType>" and "<InstalmentDay>" plan with a "<userCategory>" user with "<cardType>" card and verifying the booking "<validationApplications_assistedCheckout>" on applications for the merchant "<merchantName>" on "<applicationName>" application using "<policyType>"
        Then I can carry out post validate operations on "<validationApplications_postCheckout>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
        # Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
        Examples:
            | userRole       | merchantName | applicationName   | currencyCode | redemptionDate  | planTotal | depositSetting | installmentType | InstalmentDay | cardType | userCategory | validationApplications_assistedCheckout                                                         | validationApplications_postCheckout                                                                                                                 | checkoutType      | validationApplications_emails                                           | policyType |
            #Managed
            | Merchant Agent | Ovolo Hotels | assisted-checkout | AUD          | 15/January/2024 | 3300      | default        | Weekly          | Wednesday     | Visa     | New          | verify-userDetails,verify_payment_plan_details,email-verification,verify-standard-refund-policy | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard   |
#             | Merchant Admin      | Ovolo Hotels | assisted-checkout | AUD          | 15/October/2024 | 3300.00   | default        | Weekly          | Wednesday     | Visa    | Existing     | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard   |
#             | Merchant Supervisor | Ovolo Hotels | assisted-checkout | AUD          | 15/August/2024  | 2000.08   | default        | Fortnightly     | Sunday        | Visa    | Existing     | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard   |
#             | Merchant Agent      | Ovolo Hotels | assisted-checkout | AUD          | 15/January/2024 | 3300      | default        | Weekly          | Wednesday     | Visa    | Existing     | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard   |

#             | Merchant Agent       | Enad Hotels | assisted-checkout | AUD | 15/January/2024 | 4000    | default | Weekly      | Friday    | Visa | New      | verify-userDetails,verify_payment_plan_details,email-verification,verify-standard-refund-policy | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Admin      | Enad Hotels | assisted-checkout | AUD | 15/January/2024 | 4000.34 | default | Weekly      | Friday    | Visa | New      | verify-userDetails,verify_payment_plan_details,email-verification,verify-standard-refund-policy | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Supervisor | Enad Hotels | assisted-checkout | AUD | 15/January/2024 | 4000.34 | default | Weekly      | Friday    | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Agent      | Enad Hotels | assisted-checkout | AUD | 15/January/2024 | 4000    | default | Weekly      | Friday    | Visa | New      | verify-userDetails,verify_payment_plan_details,email-verification,verify-standard-refund-policy | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Admin      | Enad Hotels | assisted-checkout | AUD | 15/March/2024   | 5300    | default | Monthly     | 5         | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Supervisor | Enad Hotels | assisted-checkout | AUD | 15/January/2024 | 3300.58 | default | Monthly     | 5         | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Agent      | Enad Hotels | assisted-checkout | AUD | 15/January/2024 | 3300    | default | Fortnightly | Wednesday | Visa | New      | verify-userDetails,verify_payment_plan_details,email-verification,verify-standard-refund-policy | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |

#             | Merchant Agent       | Noraa Travel | assisted-checkout | AUD | 15/January/2024 | 3300    | default | Weekly      | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification  | Standard |
#             | Merchant Admin      | Noraa Travel | assisted-checkout | AUD | 15/March/2024   | 5300.09 | default | Fortnightly | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification  | Standard |
#             | Merchant Supervisor | Noraa Travel | assisted-checkout | AUD | 24/January/2024 | 3300    | default | Monthly     | 5         | Visa | New      | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy,email-verification | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification, | Standard |
#             | Merchant Agent      | Noraa Travel | assisted-checkout | AUD | 15/January/2024 | 1200.34 | default | Monthly     | 11        | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification, | Standard |

#             | Merchant Agent       | Shonrate Hotels | assisted-checkout | AUD | 15/January/2024 | 3300 | default | Weekly      | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Admin      | Shonrate Hotels | assisted-checkout | AUD | 23/March/2024   | 5300 | default | Fortnightly | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Supervisor | Shonrate Hotels | assisted-checkout | AUD | 15/January/2024 | 3300 | default | Monthly     | 5         | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy,email-verification | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |

#             | Merchant Agent       | Assilem Hotels | assisted-checkout | USD | 15/May/2024   | 1200.08 | default | Weekly      | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Admin      | Assilem Hotels | assisted-checkout | USD | 18/March/2024 | 4500    | default | Fortnightly | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Supervisor | Assilem Hotels | assisted-checkout | USD | 15/June/2024  | 1500    | default | Monthly     | 5         | Visa | New      | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy,email-verification | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |

#             | Merchant Agent       | YapNalp Hotels | assisted-checkout | AUD | 20/August/2024  | 3300.08 | default | Weekly      | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Admin      | YapNalp Hotels | assisted-checkout | AUD | 23/March/2024   | 5300    | default | Fortnightly | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Supervisor | YapNalp Hotels | assisted-checkout | AUD | 11/August/2024  | 5000    | default | Monthly     | 5         | Visa | New      | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy,email-verification | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             #Enterprise
#             | Merchant Agent      | Ideyas Hotels  | assisted-checkout | AUD | 15/January/2024 | 3300.08 | default | Weekly      | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Admin      | Ideyas Hotels  | assisted-checkout | NZD | 15/March/2024   | 5300    | default | Fortnightly | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Supervisor | Ideyas Hotels  | assisted-checkout | GBP | 15/January/2024 | 3300    | default | Monthly     | 5         | Visa | New      | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy,email-verification | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Agent      | Rotvic Hotels  | assisted-checkout | AUD | 15/January/2024 | 3300    | default | Weekly      | Wednesday | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Supervisor       | Ideyas Hotels  | assisted-checkout | AUD | 15/March/2024   | 3300.99 | default | Monthly     | 12        | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             #Enterprise Ayden Merchant
#             | Merchant Admin      | Leinad Hotels  | assisted-checkout | AUD | 15/March/2024   | 3300.99 | default | Monthly     | 12        | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |
#             | Merchant Agent       | Minty Hotels   | assisted-checkout | AUD | 15/March/2024   | 3300.99 | default | Monthly     | 12        | Visa | Existing | verify-userDetails,verify_payment_plan_details,verify-standard-refund-policy                    | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | assisted-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification | Standard |

#     Scenario: Perform n number of transaction for merchant checkout - On Schedule
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplicationstransaction>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         #     Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#             | merchantName | nTransactions | finalStatus | validationApplicationstransaction                                                                                     | checkoutType      | validationApplications_emails                    |
#             # #         #Managed
#             | Ovolo Hotels | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
# #         | Enad Hotels     | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         | Noraa Travel    | 1             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         | Shonrate Hotels | 4             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         | Assilem Hotels  | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         | YapNalp Hotels  | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         #Enterprise
#         | Rotvic Hotels   | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         | Ideyas Hotels   | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         | Leinad Hotels   | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |
#         | Minty Hotels    | 2             | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification |

# Scenario: Perform n number of transaction for merchant checkout - Completed
#     Then I can process "<nTransactions>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplicationstransaction>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Examples:
#         | merchantName    | nTransactions | finalStatus | validationApplicationstransaction                                                                                                                        | checkoutType      | validationApplications_emails                                                                                                |
#         ###Managed
#         | Enad Hotels     | 3             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | Noraa Travel    | 5             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | Ovolo Hotels    | 3             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | Shonrate Hotels | 1             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | Assilem Hotels  | 1             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | YapNalp Hotels  | 1             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         ###Enterprise
#         | Rotvic Hotels   | 1             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | Ideyas Hotels   | 1             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | Leinad Hotels   | 1             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#         | Minty Hotels    | 1             | Completed   | events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,events-transactions-eligible-merchantPayable,admin-portal | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |

# Scenario: Cancelling a Plan
#     Then As a Merchant, I can cancel the plan with "<cancellationReason>" "<finalCancellation>" reason for "<merchantName>" and verify "<screens>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_postCancellation>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Examples:
#         | merchantName    | screens                    | cancellationReason                             | finalCancellation                 | validationApplications_postCancellation                                                                                             | checkoutType      | validationApplications_emails                                               |
#         ###Managed
#         | Enad Hotels     | cancellation_summary_popup | Customer requested to cancel                   | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Enad Hotels     | cancellation_summary_popup | Payments have not been received                | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Ovolo Hotels    | cancellation_summary_popup | Customer requested to cancel                   | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Ovolo Hotels    | cancellation_summary_popup | Payments have not been received                | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Noraa Travel    | cancellation_summary_popup | We can no longer take this Booking/Reservation | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Noraa Travel    | cancellation_summary_popup | We can no longer take this Booking/Reservation | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Shonrate Hotels | cancellation_summary_popup | Payments have not been received                | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Shonrate Hotels | cancellation_summary_popup | Payments have not been received                | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Assilem Hotels  | cancellation_summary_popup | Customer requested to cancel                   | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Assilem Hotels  | cancellation_summary_popup | Customer requested to cancel                   | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | YapNalp Hotels  | cancellation_summary_popup | We can no longer take this Booking/Reservation | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | YapNalp Hotels  | cancellation_summary_popup | We can no longer take this Booking/Reservation | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         ###Enterprise
#         | Rotvic Hotels   | cancellation_summary_popup | Customer requested to cancel                   | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Rotvic Hotels   | cancellation_summary_popup | Customer requested to cancel                   | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Ideyas Hotels   | cancellation_summary_popup | Payments have not been received                | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Ideyas Hotels   | cancellation_summary_popup | Payments have not been received                | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Leinad Hotels   | cancellation_summary_popup | Payments have not been received                | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#         | Minty Hotels    | cancellation_summary_popup | Payments have not been received                | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,verifyCancellation-merchant-portal,verifyCancellation-customer-portal | assisted-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |

# Scenario: Pay Early Instalments at the plan level on the customer-portal
#     Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#     When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_postPayInstalment>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Examples:

#         | merchantName | customerUser | keepMeSignedIn | applicationName | nTransactions_UI | operation_type | screens | checkoutType | validationApplications_postPayInstalment | validationApplications_emails |

#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Managed Hotels   %%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#         | YapNalp Hotels  |  | true | customer-portal | 1 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | EKÄJ Hotel      |  | true | customer-portal | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | ÏRTIMID Hotel   |  | true | customer-portal | 3 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Ñaamra Hotel    |  | true | customer-portal | 1 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Shonrate Hotels |  | true | customer-portal | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Enad Hotels     |  | true | customer-portal | 3 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Ovolo Hotels    |  | true | customer-portal | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Noraa Travel    |  | true | customer-portal | 3 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |

#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Enterprise Hotels   %%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#         | Ideyas Hotels |  | true | customer-portal | 1 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,p,customer-portal,merchant-portal,admin-portal                            | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Nosaj Agency  |  | true | customer-portal | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,customer-portal,merchant-portal,admin-portal                              | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Idnib Flights |  | true | customer-portal | 3 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,customer-portal,merchant-portal,admin-portal                              | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | ROTVIC Hotels |  | true | customer-portal | 4 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Leinad Hotels |  | true | customer-portal | 4 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#         | Minty Hotels |  | true | customer-portal | 4 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |

# Scenario: Pay instalments using debug + Customer-portal
#     Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_on_debugendpoint>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_on_pay_UI>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Examples:
#         | merchantName | customerUser | keepMeSignedIn | applicationName | nTransactions_debug | nTransactions_UI | operation_type | screens | checkoutType | validationApplications_on_debugendpoint | validationApplications_on_pay_UI | finalStatus |

#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Managed Hotels   %%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#         | YapNalp Hotels  |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | EKÄJ Hotel      |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | ÏRTIMID Hotel   |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Ñaamra Hotel    |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Shonrate Hotels |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Enad Hotels     |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Ovolo Hotels    |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Noraa Travel    |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |

#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Enterprise Hotels   %%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#         | Ideyas Hotels |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Nosaj Agency  |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Idnib Flights |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | ROTVIC Hotels |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Leinad Hotels |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#         | Minty Hotels |  | true | customer-portal | 1 | 2 | pay-instalment | make-payment-popup,make-payment-review,payment-completed | assisted-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |

# Scenario: Update Cadence at the plan level
#     Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#     When I can successfully update the plan cadence with "<cadenceOption>" with "<InstalmentDay>" for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_postUpdateCadence>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout

#     Examples:
#         | merchantName | customerUser | keepMeSignedIn | applicationName | cadenceOption | InstalmentDay | screens | validationApplications_postUpdateCadence | checkoutType | validationApplications_emails |

#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Managed Hotels   %%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#         | YapNalp Hotels  |  | true | customer-portal | Fortnightly | Monday    | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | EKÄJ Hotel      |  | true | customer-portal | Weekly      | Friday    | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | ÏRTIMID Hotel   |  | true | customer-portal | Monthly     | 15        | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Ñaamra Hotel    |  | true | customer-portal | Fortnightly | Tuesday   | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Shonrate Hotels |  | true | customer-portal | Weekly      | Tuesday   | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Enad Hotels     |  | true | customer-portal | Monthly     | 22        | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Ovolo Hotels    |  | true | customer-portal | Fortnightly | Wednesday | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Noraa Travel    |  | true | customer-portal | Weekly      | Wednesday | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |

#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Enterprise Hotels   %%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#         | Ideyas Hotels |  | true | customer-portal | Fortnightly | Monday  | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Nosaj Agency  |  | true | customer-portal | Weekly      | Friday  | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Idnib Flights |  | true | customer-portal | Monthly     | 15      | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | ROTVIC Hotels |  | true | customer-portal | Fortnightly | Tuesday | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Leinad Hotels |  | true | customer-portal | Fortnightly | Tuesday | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |
#         | Minty Hotels |  | true | customer-portal | Fortnightly | Tuesday | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | assisted-checkout | CustomerPlanChangedSendCustomerNotification |

# Scenario: Process transaction - Late + Pay on UI
#     When I can successfully add "<paymentMethods_before>" with card status "<cardStatus>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#     Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_postCheckout_before>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     When I can successfully add "<paymentMethods_after>" with card status "<cardStatus_after>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#     When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_postCheckout>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Examples:

#         | merchantName    | cardStatus | paymentMethods_before | planIDs | nTransactions_debug | nTransactions_UI | finalStatus | validationApplications_postCheckout_before                                             | validationApplications_postCheckout                                                                                                                       | paymentMethods_after | cardStatus_after | latePayments | validationApplicationstransaction_late | checkoutType      | operation_type | screens                                                  |
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Managed Hotels   %%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         | YapNalp Hotels  | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | EKÄJ Hotel      | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | ÏRTIMID Hotel   | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Ñaamra Hotel    | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Shonrate Hotels | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Enad Hotels     | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Ovolo Hotels    | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Noraa Travel    | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Ideyas Hotels   | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,events-transactions-planChanged                              | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Nosaj Agency    | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,events-transactions-planChanged                              | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Idnib Flights   | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,events-transactions-planChanged                              | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | ROTVIC Hotels   | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Leinad Hotels   | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#         | Minty Hotels   | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment | Visa                 | valid            | 1            | Merchant-portal                        | assisted-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |

# Scenario: Merchant Re-try for Managed
#     When I can successfully add "<paymentMethods_before>" with card status "<cardStatus>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#     Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_postCheckout_before>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     When As a Merchant, I can retry the failed transactions for the "<planIDs>" plan for "<merchantName>"  using "<checkoutType>" checkout
#     When I can successfully add "<paymentMethods_after>" with card status "<cardStatus_after>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#     Then I can process "<latePayments>" late payments for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Then I can carry out post validate operations on "<validationApplications_postCheckout_after>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#     Examples:
#         | merchantName | cardStatus | paymentMethods_before | planIDs | nTransactions | finalStatus | validationApplications_postCheckout_before | validationApplications_postCheckout_after | paymentMethods_after | cardStatus_after | latePayments | validationApplicationstransaction_late | checkoutType |
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%% Assisted Checkout Managed Hotels   %%%%%%%%%%%%%%%%%%%%%%%%%
#         # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#         | YapNalp Hotels  | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | EKÄJ Hotel      | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | ÏRTIMID Hotel   | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Ñaamra Hotel    | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Shonrate Hotels | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Enad Hotels     | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Ovolo Hotels    | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Noraa Travel    | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Ideyas Hotels   | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Nosaj Agency    | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Idnib Flights   | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | ROTVIC Hotels   | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Leinad Hotels   | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |
#         | Minty Hotels   | decline | Visa |  | 1 | Late | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa | valid | 1 | Merchant-portal | assisted-checkout |




