Feature:  Demo Test Suite

        @test

        Scenario: Verify the creation of plan using checkout
                Given As a user I can navigate to the "<merchantName>" merchant on the "<applicationName>" application
                When I can successfully checkout items "<producItem>" with "<Quantity>" having "<redemptionDate>" date with currency "<checkoutCurrency>" and selected settings "<depositSetting>","<installmentType_checkout_widget>","<installmentType_checkout_summary>", "<InstalmentDay>" plan with a "<userCategory>" user with "<cardType>" card and verifying the booking "<validationApplications_onCheckout>" on applications for the merchant "<merchantName>" on "<applicationName>" application
                Then I can carry out post validate operations on "<validationApplications_postCheckout>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
                # # Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout

                Examples:
                        | merchantName    | applicationName  | producItem                                                                                                                                                                                                                                  | Quantity  | redemptionDate                                                                  | depositSetting | installmentType_checkout_widget | installmentType_checkout_summary | InstalmentDay | userCategory | cardType   | validationApplications_onCheckout                                                                                | validationApplications_postCheckout                                                                                                                 | checkoutCurrency | checkoutType      | validationApplications_emails                                           |
                        | Enad Hotels     | merchant-testing | Holiday                                                                                                                                                                                                                                     | 1         | 10/December/2024                                                                | max            | Monthly                         | Monthly                          | 29            | New          | MasterCard | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary,AccountSetupSendWelcomeNotification | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | Ovolo Hotels    | merchant-testing | Wedding dress                                                                                                                                                                                                                               | 1         | 20/December/2023                                                                | random         | Weekly                          | Fortnightly                      | Sunday        | New          | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | Noraa Travel    | merchant-testing | Airline flight$Hotel booking                                                                                                                                                                                                                | 1,2       | 20/December/2023,1/November/2024                                                | random         | Monthly                         | Monthly                          | 30            | New          | MasterCard | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | Shonrate Hotels | merchant-testing | Superior Deluxe King Guest room 1 King                                                                                                                                                                                                      | 2         | 24/December/2023                                                                | default        | Weekly                          | Fortnightly                      | Monday        | Existing     | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | YapNalp Hotels  | merchant-testing | Club King Club lounge access Guest room 1 King                                                                                                                                                                                              | 2         | 20/December/2023                                                                | min            | Weekly                          | Monthly                          | 1             | Existing     | American   | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | EKÄJ Hotel      | merchant-testing | Superior Deluxe King Guest room 1 King                                                                                                                                                                                                      | 2         | 20/October/2024                                                                 | default        | Weekly                          | Fortnightly                      | Friday        | Existing     | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal                              | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | ÏRTIMID Hotel   | merchant-testing | Superior Deluxe King Guest room 1 King                                                                                                                                                                                                      | 2         | 20/October/2024                                                                 | random         | Weekly                          | Fortnightly                      | Thursday      | Existing     | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal                              | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | Ñaamra Hotel    | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s)$Superior Studio Twin Larger Guest room 2 Double$Club King Club lounge access Guest room 1 King$Presidential Suite Club lounge access High floor | 1,3,1,1,1 | 20/November/2024,21/November/2024,22/March/2024,25/November/2024,1/January/2024 | default        | Fortnightly                     | Weekly                           | Tuesday       | Existing     | MasterCard | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal                              | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | Assilem Hotels  | merchant-testing | Holiday                                                                                                                                                                                                                                     | 1         | 30/June/2024                                                                    | random         | Monthly                         | Monthly                          | 31            | Existing     | MasterCard | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | USD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | YapNalp Hotels  | merchant-testing | Superior Deluxe Twin Guest room 2 Twin/Single Bed(s)$Superior Studio Twin Larger Guest room 2 Double$Club King Club lounge access Guest room 1 King                                                                                         | 1,1,1     | 27/December/2023,1/October/2024,25/October/2024                                 | default        | Weekly                          | Weekly                           | Friday        | Existing     | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary                                     | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |


# Scenario: Process successful transactions using debug endpoint - On Schedule
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplicationstransaction>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
# Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
# Examples:
#         | merchantName   | nTransactions_debug | finalStatus | validationApplicationstransaction                                                                                     | checkoutType      | validationApplications_emails                    |
# | Enad Hotels     | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | Ovolo Hotels    | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | Noraa Travel   | 1                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | Shonrate Hotels | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | YapNalp Hotels | 1                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | EKÄJ Hotel     | 1                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | ÏRTIMID Hotel   | 1                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | Ñaamra Hotel    | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
# | Assilem Hotels  | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |

# Scenario: Trigger Overdue payments and pay using debug endpoint
#         When I can successfully add "<paymentMethods_before>" with card status "<cardStatus>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postCheckout_before>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When I can successfully add "<paymentMethods_after>" with card status "<cardStatus_after>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#         Then I can process "<latePayments>" late payments for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postCheckout_after>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName    | cardStatus | paymentMethods_before | planIDs | nTransactions_debug | finalStatus | validationApplications_postCheckout_before                                             | validationApplications_postCheckout_after                                                                             | paymentMethods_after | cardStatus_after | latePayments | validationApplicationstransaction_late | checkoutType      | validationApplications_emails                    |
#                 | Enad Hotels     | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | Ovolo Hotels    | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | Noraa Travel    | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | Shonrate Hotels | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | YapNalp Hotels  | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | EKÄJ Hotel      | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | ÏRTIMID Hotel   | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | Ñaamra Hotel    | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |
#                 | Assilem Hotels  | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | American             | valid            | 1            | Merchant-portal                        | customer-checkout | CustomerPaymentSucceededSendCustomerNotification |

# Scenario: Pay Early Instalments at the plan level on the customer-portal
#         Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postPayInstalment>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         # Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName   | customerUser | keepMeSignedIn | applicationName | nTransactions_UI | operation_type | screens                                                  | checkoutType      | validationApplications_postPayInstalment                                                                                                              | validationApplications_emails                           |
#                 | Enad Hotels     |              | true           | customer-portal | 1                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Ovolo Hotels    |              | true           | customer-portal | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
# | Noraa Travel   |              | true           | customer-portal | 1                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Shonrate Hotels |              | true           | customer-portal | 1                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
# | YapNalp Hotels |              | true           | customer-portal | 1                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
# | EKÄJ Hotel     |              | true           | customer-portal | 1                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal                              | CustomerAdvancePaymentSucceededSendCustomerNotification |
# | ÏRTIMID Hotel   |              | true           | customer-portal | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal                              | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Ñaamra Hotel    |              | true           | customer-portal | 3                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal                              | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Assilem Hotels  |              | true           | customer-portal | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |

# Scenario: Process successful transactions using debug endpoint  + Pay Early Customer-portal
#         Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_on_debugendpoint>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_on_pay_UI>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName    | customerUser | keepMeSignedIn | applicationName | nTransactions_debug | nTransactions_UI | operation_type | screens                                                  | checkoutType      | validationApplications_on_debugendpoint                                                                                                                                | validationApplications_on_pay_UI                                             | finalStatus |
#                 | Enad Hotels     |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Ovolo Hotels    |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Noraa Travel    |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Shonrate Hotels |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | YapNalp Hotels  |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | EKÄJ Hotel      |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | ÏRTIMID Hotel   |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Ñaamra Hotel    |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Assilem Hotels  |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |

# Scenario: Update Cadence at the plan level
#         Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When I can successfully update the plan cadence with "<cadenceOption>" with "<InstalmentDay>" for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postUpdateCadence>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName    | customerUser | keepMeSignedIn | applicationName | cadenceOption | InstalmentDay | screens                                             | validationApplications_postUpdateCadence                                     | checkoutType      | validationApplications_emails               |
#                 | Enad Hotels     |              | true           | customer-portal | Fortnightly   | Monday        | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Ovolo Hotels    |              | true           | customer-portal | Weekly        | Friday        | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Noraa Travel    |              | true           | customer-portal | Monthly       | 15            | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Shonrate Hotels |              | true           | customer-portal | Fortnightly   | Tuesday       | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | YapNalp Hotels  |              | true           | customer-portal | Weekly        | Tuesday       | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | EKÄJ Hotel      |              | true           | customer-portal | Monthly       | 22            | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal                              | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | ÏRTIMID Hotel   |              | true           | customer-portal | Fortnightly   | Wednesday     | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal                              | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Ñaamra Hotel    |              | true           | customer-portal | Weekly        | Wednesday     | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal                              | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Assilem Hotels  |              | true           | customer-portal | Weekly        | Wednesday     | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |

# Scenario: Process transaction - Late + Pay on UI
#         When I can successfully add "<paymentMethods_before>" with card status "<cardStatus>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postCheckout_before>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When I can successfully add "<paymentMethods_after>" with card status "<cardStatus_after>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#         When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postCheckout>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName    | cardStatus | paymentMethods_before | planIDs | nTransactions_debug | nTransactions_UI | finalStatus | validationApplications_postCheckout_before                                             | validationApplications_postCheckout                                                                                                                       | paymentMethods_after | cardStatus_after | latePayments | validationApplicationstransaction_late | checkoutType      | operation_type | screens                                                  |
#                 | Enad Hotels     | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | Ovolo Hotels    | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | Noraa Travel    | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | Shonrate Hotels | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | YapNalp Hotels  | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | EKÄJ Hotel      | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | ÏRTIMID Hotel   | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | Ñaamra Hotel    | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |
#                 | Assilem Hotels  | decline    | Visa                  |         | 1                   | 1                | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,events-transactions-planChanged | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout | pay-instalment | make-payment-popup,make-payment-review,payment-completed |

# Scenario: Merchant Re-try for Managed
#         When I can successfully add "<paymentMethods_before>" with card status "<cardStatus>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postCheckout_before>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When As a Merchant, I can retry the failed transactions for the "<planIDs>" plan for "<merchantName>"  using "<checkoutType>" checkout
#         When I can successfully add "<paymentMethods_after>" with card status "<cardStatus_after>" for "<planIDs>" plans for "<merchantName>" merchant using "<checkoutType>" checkout
#         When As a Merchant, I can retry the failed transactions for the "<planIDs>" plan for "<merchantName>"  using "<checkoutType>" checkout
# Then I can carry out post validate operations on "<validationApplications_postCheckout_after>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
# Examples:

#         | merchantName   | cardStatus | paymentMethods_before | planIDs | nTransactions_debug | finalStatus | validationApplications_postCheckout_before                                             | validationApplications_postCheckout_after                                                                                                 | paymentMethods_after | cardStatus_after | latePayments | validationApplicationstransaction_late | checkoutType      |
#                 | Enad Hotels     | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout |
#                 | Ovolo Hotels    | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout |
# | Noraa Travel   | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout |
#                 | Shonrate Hotels | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout |
# | YapNalp Hotels | decline    | Visa                  |         | 1                   | Late        | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal | Visa                 | valid            | 1            | Merchant-portal                        | customer-checkout |

# Scenario: Process transactions - Completed
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplicationstransaction>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         # Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can verify the transactions are balancing out for the "<plan>" or the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can move the plan "<finalStatus>" status "<merchantName>" and "<checkoutType>"
#         Then I can carry out post validate operations on "<validationApplicationsonPayable>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName    | nTransactions_debug | finalStatus | validationApplicationstransaction                                                                                     | plan | checkoutType      | validationApplicationsonPayable              | validationApplications_emails                                                                                 |
#                 | Enad Hotels     | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
#                 | Ovolo Hotels    | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
# | Noraa Travel    | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
#                 | Shonrate Hotels | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
# | YapNalp Hotels  | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
# | EKÄJ Hotel      | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
#                 | ÏRTIMID Hotel   | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
#                 | Ñaamra Hotel    | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |
#                 | Assilem Hotels  | 3                   | Completed   | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | events-transactions-eligible-merchantPayable | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification,events-transactions-planCompleted |


# Scenario: Cancelling a Plan
#         Then As a Merchant, I can cancel the plan with "<cancellationReason>" "<finalCancellation>" reason for "<merchantName>" and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postCancellation>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         # Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName   | screens                                                 | cancellationReason                             | finalCancellation                 | validationApplications_postCancellation                                                                    | checkoutType      | validationApplications_emails                                               |
#                 #                 | Enad Hotels     | cancellation_summary_popup,how_this_is_calculated_popup | Customer requested to cancel                   | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#                 #                 | Ovolo Hotels    | cancellation_summary_popup,how_this_is_calculated_popup | Customer requested to cancel                   | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#                 | Noraa Travel   | cancellation_summary_popup,how_this_is_calculated_popup | We can no longer take this Booking/Reservation | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#                 #                 | Shonrate Hotels | cancellation_summary_popup,how_this_is_calculated_popup | We can no longer take this Booking/Reservation | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#                 | YapNalp Hotels | cancellation_summary_popup,how_this_is_calculated_popup | Payments have not been received                | Cancel and refund a custom amount | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |

# Scenario: Verify payment Methods added at Checkout
#         Given As a user I can navigate to the "<merchantName>" merchant on the "<applicationName>" application
#         When I can successfully checkout items "<producItem>" with "<Quantity>" having "<redemptionDate>" date with "<checkoutCurrency>" and selected settings "<depositSetting>","<installmentType_checkout_widget>","<installmentType_checkout_summary>", "<InstalmentDay>" plan with a "<userCategory>" user with "<defaultCardType>" card and additional "<paymentMethods>" for "<merchantName>" and "<checkoutType>"
#         Examples:
#                 | merchantName    | applicationName  | producItem                                                                                  | Quantity | redemptionDate                   | depositSetting | installmentType_checkout_widget | installmentType_checkout_summary | InstalmentDay | userCategory | defaultCardType | paymentMethods      | checkoutCurrency | checkoutType      |
#                 | Enad Hotels     | merchant-testing | Holiday                                                                                     | 1        | 15/October/2024                  | default        | Weekly                          | Fortnightly                      | Saturday      | New          | MasterCard      | Visa,American       | AUD              | customer-checkout |
#                 | Ovolo Hotels    | merchant-testing | Wedding veil$Wedding shoes                                                                  | 2,1      | 15/December/2024,10/October/2024 | random         | Fortnightly                     | Weekly                           | Thursday      | New          | Visa            | American,MasterCard | AUD              | customer-checkout |
#                 | Noraa Travel    | merchant-testing | Airline flight$Hotel booking                                                                | 1,2      | 15/December/2024,10/October/2024 | max            | Fortnightly                     | Monthly                          | 30            | New          | Visa            | American,MasterCard | AUD              | customer-checkout |
#                 | Shonrate Hotels | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s) | 1,3      | 15/December/2024,10/October/2024 | default        | Monthly                         | Weekly                           | Friday        | New          | Visa            | American,MasterCard | AUD              | customer-checkout |
#                 | YapNalp Hotels  | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s) | 1,3      | 15/December/2024,10/October/2024 | default        | Monthly                         | Weekly                           | Friday        | New          | Visa            | American,MasterCard | AUD              | customer-checkout |
#                 | EKÄJ Hotel      | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s) | 1,3      | 15/December/2024,10/October/2024 | default        | Monthly                         | Monthly                          | 15            | New          | Visa            | American,MasterCard | AUD              | customer-checkout |
#                 | ÏRTIMID Hotel   | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s) | 1,3      | 15/December/2024,10/October/2024 | default        | Monthly                         | Weekly                           | Friday        | New          | Visa            | American,MasterCard | AUD              | customer-checkout |
#                 | Assilem Hotels  | merchant-testing | Holiday                                                                                     | 1        | 1/February/2024                  | default        | Weekly                          | Monthly                          | 29            | New          | MasterCard      | Visa,American       | AUD              | customer-checkout |
