Feature: Smoke test file for enterprise merchants

        Scenario: Verify the creation of plan using checkout
                Given As a user I can navigate to the "<merchantName>" merchant on the "<applicationName>" application
                When I can successfully checkout items "<producItem>" with "<Quantity>" having "<redemptionDate>" date with currency "<checkoutCurrency>" and selected settings "<depositSetting>","<installmentType_checkout_widget>","<installmentType_checkout_summary>", "<InstalmentDay>" plan with a "<userCategory>" user with "<cardType>" card and verifying the booking "<validationApplications_onCheckout>" on applications for the merchant "<merchantName>" on "<applicationName>" application
                Then I can carry out post validate operations on "<validationApplications_postCheckout>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
                # Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
                Examples:
                        | merchantName  | applicationName  | producItem                                                                             | Quantity | redemptionDate                  | depositSetting | installmentType_checkout_widget | installmentType_checkout_summary | InstalmentDay | userCategory | cardType   | validationApplications_onCheckout                                            | validationApplications_postCheckout                                                                                                                 | checkoutCurrency | checkoutType      | validationApplications_emails                                           |
                        | Ideyas Hotels | merchant-testing | Holiday                                                                                | 1        | 24/October/2024                 | default        | Weekly                          | Weekly                           | Thursday      | New          | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary | events-transactions-planCreated,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal                            | NZD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | Nosaj Agency  | merchant-testing | Holiday                                                                                | 1        | 30/October/2024                 | max            | Monthly                         | Monthly                          | 31            | New          | MasterCard | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary | events-transactions-planCreated,events-transactions-due-requested-succeeded,customer-portal                                                         | GBP              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | Idnib Flights | merchant-testing | Holiday                                                                                | 1        | 24/October/2024                 | random         | Fortnightly                     | Weekly                           | Thursday      | Existing     | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary | events-transactions-planCreated,events-transactions-due-requested-succeeded,customer-portal                                                         | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        | ROTVIC Hotels | merchant-testing | Superior Deluxe King Guest room 1 King                                                 | 1        | 24/October/2024                 | min            | Weekly                          | Fortnightly                      | Thursday      | Existing     | Visa       | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary | events-transactions-planCreated,events-transactions-due-requested-succeeded,paymentHistory-planCreated,customer-portal,merchant-portal,admin-portal | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        ## Adyan Payment Gatway
                        | Leinad Hotels | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Studio Twin Larger Guest room 2 Double | 1,2      | 1/December/2023,1/November/2024 | random         | Weekly                          | Monthly                          | 30            | New          | MasterCard | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary | events-transactions-planCreated,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal                            | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |
                        ## Mint Payment Gatway
                        | Minty Hotels  | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Studio Twin Larger Guest room 2 Double | 1,2      | 1/December/2023,1/November/2024 | random         | Weekly                          | Monthly                          | 30            | New          | MasterCard | price_preview_widget,price_preview_widget_2,checkout_widget,checkout_summary | events-transactions-planCreated,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal                            | AUD              | customer-checkout | PlanCreatedSendMerchantNotification,PlanCreatedSendCustomerNotification |





# Scenario: Process successful transactions/Trigger Overdue payments using debug endpoint
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplicationstransaction>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_failedPayment>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName  | nTransactions_debug | finalStatus | validationApplicationstransaction                                                                                     | checkoutType      | validationApplications_emails                    | validationApplications_failedPayment |
#                 | Ideyas Hotels | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed |
#                 | Nosaj Agency  | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | customer-checkout | CustomerPaymentSucceededSendCustomerNotification | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed |
#                 | Idnib Flights | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal                              | customer-checkout | CustomerPaymentSucceededSendCustomerNotification | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed |
#                 | ROTVIC Hotels | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed |
#                 | Leinad Hotels | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed |
#                 | Minty Hotels  | 3                   | On Schedule | events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPaymentSucceededSendCustomerNotification | CustomerPaymentFailedSendCustomerNotification,events-transactions-due-requested-failed |


# Scenario: Pay Early Instalments at the plan level on the customer-portal
#         Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
# #         Then I can carry out post validate operations on "<validationApplications_postPayInstalment>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
# #         Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName  | customerUser | keepMeSignedIn | applicationName | nTransactions_UI | operation_type | screens                                                  | checkoutType      | validationApplications_postPayInstalment                                                                                                              | validationApplications_emails                           |
# #               | Ideyas Hotels |              | true           | customer-portal | 1                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,customer-portal,merchant-portal,admin-portal                              | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Nosaj Agency  |              | true           | customer-portal | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,customer-portal                                                           | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Idnib Flights |              | true           | customer-portal | 3                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,customer-portal                                                           | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | ROTVIC Hotels |              | true           | customer-portal | 4                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Leinad Hotels |              | true           | customer-portal | 4                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |
#                 | Minty Hotels   |              | true           | customer-portal | 4                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | events-transactions-due-requested-succeeded,events-transactions-planChanged,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | CustomerAdvancePaymentSucceededSendCustomerNotification |

# Scenario: Pay instalments using debug + Customer-portal
#         Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_on_debugendpoint>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         When I can process on customer-portal "<nTransactions_UI>" payments using operation "<operation_type>" on for plans for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_on_pay_UI>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName  | customerUser | keepMeSignedIn | applicationName | nTransactions_debug | nTransactions_UI | operation_type | screens                                                  | checkoutType      | validationApplications_on_debugendpoint                                                                                                                                | validationApplications_on_pay_UI                                             | finalStatus |
#                 | Ideyas Hotels |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal,merchant-portal,admin-portal                              | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Nosaj Agency  |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal                                                           | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Idnib Flights |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,customer-portal                                                           | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | ROTVIC Hotels |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Leinad Hotels |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |
#                 | Minty Hotels   |              | true           | customer-portal | 1                   | 2                | pay-instalment | make-payment-popup,make-payment-review,payment-completed | customer-checkout | CustomerPaymentSucceededSendCustomerNotification,events-transactions-due-requested-succeeded,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | On Schedule |


# Scenario: Update Cadence at the plan level
# Given As a "<customerUser>" Customer portal user having "<keepMeSignedIn>" keepMeSignedIn setting I can successfully login to the "<applicationName>" application for the merchant "<merchantName>" using "<checkoutType>" checkout
# When I can successfully update the plan cadence with "<cadenceOption>" with "<InstalmentDay>" for "<merchantName>" merchant and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postUpdateCadence>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout

# Examples:
# | merchantName  | customerUser | keepMeSignedIn | applicationName | cadenceOption | InstalmentDay | screens                                             | validationApplications_postUpdateCadence                                     | checkoutType      | validationApplications_emails               |
#                 | Ideyas Hotels |              | true           | customer-portal | Fortnightly   | Monday        | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
# | Nosaj Agency  |              | true           | customer-portal | Weekly        | Friday        | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal                              | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Idnib Flights |              | true           | customer-portal | Monthly       | 15            | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal                              | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | ROTVIC Hotels |              | true           | customer-portal | Fortnightly   | Tuesday       | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Leinad Hotels |              | true           | customer-portal | Fortnightly   | Tuesday       | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |
#                 | Minty Hotels   |              | true           | customer-portal | Fortnightly   | Tuesday       | update-plan-overview,update-plan-recap,plan_updated | events-transactions-planChanged,customer-portal,merchant-portal,admin-portal | customer-checkout | CustomerPlanChangedSendCustomerNotification |



# Scenario: Process transactions - Completed
#         Then I can process using debug endpoint "<nTransactions_debug>" payments with "<finalStatus>" order status for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplicationstransaction>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can verify the transactions are balancing out for the "<plan>" or the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName  | nTransactions_debug | finalStatus | validationApplicationstransaction                                                                                                                                                              | plan | checkoutType      | validationApplications_emails                                               |
#                 | Ideyas Hotels | 3                   | Completed   | events-transactions-due-requested-succeeded,events-transactions-revenueRecognition,events-transactions-planCompleted,customer-portal,merchant-portal,admin-portal                              | ALL  | customer-checkout | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#                 | Nosaj Agency  | 3                   | Completed   | events-transactions-due-requested-succeeded,events-transactions-revenueRecognition,events-transactions-planCompleted,customer-portal                                                           | ALL  | customer-checkout | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#                 | Idnib Flights | 3                   | Completed   | events-transactions-due-requested-succeeded,events-transactions-revenueRecognition,events-transactions-planCompleted,customer-portal                                                           | ALL  | customer-checkout | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#                 | ROTVIC Hotels | 3                   | Completed   | events-transactions-due-requested-succeeded,events-transactions-revenueRecognition,events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#                 | Leinad Hotels | 3                   | Completed   | events-transactions-due-requested-succeeded,events-transactions-revenueRecognition,events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |
#                 | Minty Hotels  | 3                   | Completed   | events-transactions-due-requested-succeeded,events-transactions-revenueRecognition,events-transactions-planCompleted,paymentHistory-payInstalment,customer-portal,merchant-portal,admin-portal | ALL  | customer-checkout | PlanCompletedSendCustomerNotification,PlanCompletedSendMerchantNotification |

# Scenario: Cancelling a Plan
#         Then As a Merchant, I can cancel the plan with "<cancellationReason>" "<finalCancellation>" reason for "<merchantName>" and verify "<screens>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_postCancellation>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Then I can carry out post validate operations on "<validationApplications_emails>" on applications for the merchant "<merchantName>" using "<checkoutType>" checkout
#         Examples:
#                 | merchantName  | screens                                                 | cancellationReason                             | finalCancellation                 | validationApplications_postCancellation                                                                    | checkoutType      | validationApplications_emails                                               |
#                 | Ideyas Hotels | cancellation_summary_popup,how_this_is_calculated_popup | Customer requested to cancel                   | Cancel and refund a custom amount | events-transactions-planCancelled,customer-portal,merchant-portal,admin-portal                             | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#                 | ROTVIC Hotels | cancellation_summary_popup,how_this_is_calculated_popup | We can no longer take this Booking/Reservation | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#                 | Leinad Hotels | cancellation_summary_popup,how_this_is_calculated_popup | We can no longer take this Booking/Reservation | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |
#                 | Minty Hotels  | cancellation_summary_popup,how_this_is_calculated_popup | We can no longer take this Booking/Reservation | Cancel with full refund           | events-transactions-planCancelled,paymentHistory-planRefunded,customer-portal,merchant-portal,admin-portal | customer-checkout | PlanCancelledSendMerchantNotification,PlanCancelledSendCustomerNotification |


# Scenario: Verify payment Methods added at Checkout
#         Given As a user I can navigate to the "<merchantName>" merchant on the "<applicationName>" application
#         When I can successfully checkout items "<producItem>" with "<Quantity>" having "<redemptionDate>" date with "<checkoutCurrency>" and selected settings "<depositSetting>","<installmentType_checkout_widget>","<installmentType_checkout_summary>", "<InstalmentDay>" plan with a "<userCategory>" user with "<defaultCardType>" card and additional "<paymentMethods>" for "<merchantName>" and "<checkoutType>"
#         Examples:
#                 | merchantName  | applicationName  | producItem                                                                                  | Quantity | redemptionDate                  | depositSetting | installmentType_checkout_widget | installmentType_checkout_summary | InstalmentDay | userCategory | defaultCardType | paymentMethods | checkoutCurrency | checkoutType      |
#                 | Ideyas Hotels | merchant-testing | Holiday                                                                                     | 1        | 15/October/2024                 | default        | Weekly                          | Fortnightly                      | Saturday      | New          | MasterCard      | Visa           | AUD              | customer-checkout |
#                 | Nosaj Agency  | merchant-testing | Holiday                                                                                     | 1        | 10/October/2024                | default        | Weekly                          | Weekly                           | Saturday      | New          | MasterCard      | Visa           | AUD              | customer-checkout |
#                 | Idnib Flights | merchant-testing | Holiday                                                                                     | 1        | 17/January/2024                 | default        | Weekly                          | Monthly                          | 31            | New          | MasterCard      | Visa           | AUD              | customer-checkout |
#                 | ROTVIC Hotels | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s) | 1,1      | 15/October/2024,15/December/23 | default        | Weekly                          | Monthly                          | 28            | New          | MasterCard      | Visa,American  | AUD              | customer-checkout |
#                 | Leinad Hotels | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s) | 1,1      | 15/October/2024,15/December/23 | default        | Weekly                          | Monthly                          | 28            | New          | MasterCard      | Visa,American  | AUD              | customer-checkout |
#                 | Minty Hotels  | merchant-testing | Superior Deluxe King Guest room 1 King$Superior Deluxe Twin Guest room 2 Twin/Single Bed(s) | 1,1      | 15/October/2024,15/December/23 | default        | Weekly                          | Monthly                          | 28            | New          | MasterCard      | Visa,American  | AUD              | customer-checkout |
