const config = {
  planDetails: {
    completionDate: '',
    orderDate: '',
    lastPaymentDate: '',
    totalCost: '',
    totalNoOfInstallments: '',
    numberOfInstalment: '',
    depositPaid: '',
    installmentAmount: '',
    merchantName: '',
    percentageInstallmentPaid: '',
    deposit: '',
    requiredMinimumDeposit: '',
    MaxDepositAmount: '',
    merchantActualName: '',
    OrderID: '634e90da57cbfb5e19724b84',
    productList: '',
    remainingAmount: '',
    totalFunds: '',
    noOfInstallmentsPaid: '',
    Remainder: '',
    MerchantRevenue: '',
    planpayfee: '',
    noOfInstallmentsToBePaid: '',
    MerchantFeeExclTax: '',
    MerchantFeeTax: '',
    MerchantFeeinclTax: '',
    RefundAmount: '',
  },

  MerchantEnv: {
    productList: '',
    itemPrelocator: '',
    itemPostlocator: '',
  },
  customer: {
    Email: '',
    firstName: '',
    lastName: '',
    phoneNumber: '',
    nameonCard: '',
    cardNumber: '',
    month: '',
    cvc: '',
    billingAddress: '',
    suburb: '',
    state: '',
    postCode: '',
  },
  UpcomingPayments: [],
  paidPayments: [],

  LocalEnv: {
    applicationName: '',
    merchantName: '',
  },
};
// module.exports = config;
// export default config;
