export const expectedConfig = {
  planSummary: {
    completionDate: '',
    planDate: '',
    effectiveDate: '',
    lastPaymentDate: '',
    paymentsFrom: '',
    paymentMode: '',
    totalCost: '',
    installmentPeriod: '',
    InstallmentDay: '',
    totalNoOfInstallments: '',
    numberOfInstalment: '',
    installmentAmount: '',
    priceWidget: '',
    percentageInstallmentPaid: '',
    paymentMethod: '',
    planStatus: '',
    planID: '',
    remainingAmount: '',
    totalFunds: '',
    noOfInstallmentsPaid: '',
    Remainder: '',
    noOfInstallmentsToBePaid: '',
    redemptionDate: '',
    checkoutCurrency: '',
    currencySymbol: '',
    message: '',
    paymentPlatform_vendor: '',
    paymentPlatform_variant: '',
    checkoutType: '',
    skippedAmount: '',
    skippedInstalments: '',
  },
  depositSettings: {
    depositRuleApplied: '',
    depositSetting: '',
    requiredMinimumDeposit: '',
    MaxDepositAmount: '',
    depositPaid: '',
    depositExcludingRemainder: '',
    evenInstalmentAmount: '',
    MaxDepositAmount_rounddown: '',
    requiredMinimumDeposit_roundup: '',
  },
  fees: {
    totalMerchantTransactionFee: '',
    planPayFeesSoFar: '',
    merchantRevenue: '',
    TotalServiceFeesExcGST: '',
    ServiceFeesExcGSTonPaid: '',
    MerchantRevenueExcludingFees: '',
  },
  merchantDetails: {
    merchantName: '',
    merchantId: '',
    sub_merchantName: '',
    // eslint-disable-next-line no-irregular-whitespace
    sub_merchantId: '',
    checkoutCategory: '',
  },

  cancellationDetails: {
    planCancellationDate: '',
    refundType: '',
    refundAmount: '',
    ActualRefundAmountUI: '',
    FinalNonRefundAmount: '',
    CustomerRefundValue: '',
    nonRefundableDeposit: '',
    totalNonRefundableDeposit: '',
    reason: '',
  },
  planDetails: {
    productsQuantity: [],
    productsAmount: [],
    producItem: [],
    items: [],
    poilcyType: '',
    paymentLink:{
    link:'',
    expiryDate:''
  }
  },
  flags: {
    cancelPlanFlag: 'false',
    blockedCheckout: 'false',
    eventProcessorError: 'false',
    PaymentEligible: 'false',
    blockedPayInstalment: 'false',
    updateCadenceblocked: 'false',
    selectionBlocked: 'false',
    userExists: 'false',
    latePayment: 'false',
  },
  MerchantEnv: {
    selectedMerchant: {},
    productList: '',
    itemPrelocator: '',
    itemPostlocator: '',
  },
  customer: {
    Email: '',
    firstName: '',
    lastName: '',
    phoneNumber: '',
    userVerified: 'false',
    userStatus: '',
    accountCreated: '',
    userId: '',
  },
  customerLog: {
    Email: '',
    firstName: '',
    lastName: '',
    phoneNumber: '',
  },
  UpcomingPayments: [],
  paidPayments: [
    {
      amount: '',
      date: '',
      actualPaidDate: '',
      instalment: '',
      paymentMethodUsed: '',
      status: '',
      paymentType: '',
      remainder: '',
      type: {
        Charge: {
          amountcapturedAvailable: '',
          amountRefunded: '',
        },
        Refund: {
          amountcapturedAvailable: '',
          amountRefunded: '',
        },
      },
    },
  ],
  latePayments: [],
  skippedInstallment: [],

  LocalEnv: {
    applicationName: '',
    merchantName: '',
    operationType: '',
  },
};
