export const merchantsConfig = {
  merchant: {
    id: '',
    name: '',
    companyEmail: '',
    phoneNumber: '',
    merchantSupportEmail: '',
    customerSupportEmail: '',
    merchantPageUrl: '',
    billingAddressId: '',
    defaultPaymentDeadlineInDays: '',
    serviceFeePercentage: '',
    createdAt: '',
    updatedAt: '',
    defaultMinimumDepositType: '',
    defaultMinimumDepositValue: '',
    countryAlpha3Code: '',
    status: '',
    googleAnalyticsMeasurementID: '',
    merchantGroupId: '',
    line1: '',
    line2: '',
    city: '',
    state: '',
    postcode: '',
  },
  subMerchants: [
    {
      id: '',
      name: '',
      companyEmail: '',
      phoneNumber: '',
      merchantSupportEmail: '',
      customerSupportEmail: '',
      merchantPageUrl: '',
      billingAddressId: '',
      createdAt: '',
      updatedAt: '',
      status: '',
      line1: '',
      line2: '',
      city: '',
      state: '',
      postcode: '',
    },
  ],
  MerchantDefaultRefundPolicy: [],
  MerchantPaymentPlatform: [],
  MerchantPaymentPlatformCurrency: [{}],
  LocalEnv: {
    operationType: '',
    nSubmerchant: 0,
  },
};
